config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'#, constraints: ApplicationController.new

  get 'index', to: 'users#index', defaults: { format: 'json' }

  scope '(:locale)', locale: /en|ru/ do
    resources :users, except: [:show]
    get 'signup', to: 'users#new'
    get 'verification/:id', to: 'users#verification', as: :verification
    put 'update_description', to: 'users#update_description', as: :update_description
    get 'restore_password', to: 'users#restore_password', as: :restore_password
    post 'restore', to: 'users#restore'
    get 'switch/:locale', to: 'users#switch', as: :switch
  end

  scope '(:locale)', locale: /en|ru/ do
    namespace :users do
      resources :sessions, only: [:create]
      get 'sessions', to: 'sessions#new'
      get 'login', to: 'sessions#new', as: :login
      delete 'logout/:id', to: 'sessions#destroy', as: :logout
    end
  end

  mount Api => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :ingredient_categories do
  #   resources :ingredients
  # end

  #get '/:locale' => 'users#index'
  scope '(:locale)', locale: /en|ru/ do
    root 'users#index'
    get 'parser', to: 'parser#index', constraints: ApplicationController.new
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>RecipiesSelection</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <%= javascript_include_tag 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js' %>
  <![endif]-->
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('site_name'), root_path(), class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <%#= current_user %>
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path() %>"><%= t('home') %></a></li>

        <% if current_user %>
            <li>
              <a class="margin_right_10" href="<%= edit_user_path(@current_user.slug) %>"><%= @current_user.name %></a>
            </li>
            <li>
              <a class="margin_right_10" href="<%= users_logout_path(@current_user.id) %>" data-turbolinks="false" data-method="delete"><%= t('logout') %></a>
            </li>
            <%=
              link_to t('logout'),
                      users_logout_path(1),
                      method: 'delete',
                      class: 'margin_right_10',
                      data: {no_turbolink: true}
            %>

        <% else %>
            <li><a class="margin_right_10" href="<%= users_login_path() %>"><%= t('sign_in') %></a></li>
            <li><a class="margin_right_10" href="<%= new_user_path() %>"><%= t('registration') %></a></li>
        <% end %>
        <li id="switch"><span><%= t('language') %>:</span>
          <%= link_to_unless_current 'ru', locale: 'ru' %><span class="swi">|</span><%= link_to_unless_current 'en', locale: 'en' %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? 'danger' : 'success' } alert-dismissable", role: 'alert' do %>
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only"><%= t('close') %></span></button>
          <%= msg %>
      <% end %>
  <% end %>

    <%= yield %>
    <%#= console %>
  </div>
</body>
</html>